version: "3.9"
services:
  
  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=dulces
      - MYSQL_PASSWORD=dulceria
      - MYSQL_DATABASE=wordpress
    restart: always
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=dulces
      - WORDPRESS_DB_PASSWORD=dulceria
    depends_on:
      - db
      - phpmyadmin
    restart: always
    ports:
      - 8082:80
 
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
  wordpress-cli:
    container_name: wordpress-cli
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    user: www-data
    environment:
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=dulces
      - WORDPRESS_DB_PASSWORD=dulceria
    volumes:
      - ./wordpress:/var/www/html
 
volumes:
  db_data:
  wp_data: